import logging
import os
import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path
from typing import List

from core.schema import AgentResult
from core.state import AgentState

logger = logging.getLogger(__name__)


def _smtp_configured() -> bool:
    """Return True only when all four required SMTP env vars are set and non-empty."""
    required = ["SMTP_HOST", "SMTP_USER", "SMTP_PASSWORD", "SMTP_FROM"]
    return all(os.getenv(var, "").strip() for var in required)


def _compute_mean_confidence(agent_results: List[AgentResult]) -> float:
    """Mean confidence across successful agents. Returns 0.0 for empty/all-failed."""
    scores = [r.confidence for r in agent_results if r.success]
    return sum(scores) / len(scores) if scores else 0.0


def _build_subject(state: AgentState) -> str:
    """Build email subject line.

    Format: "EDA Report: {goal} [{verdict_or_score}]"
    Goal is truncated to 60 chars if needed.
    """
    request = state["request"]
    goal = request.goal
    if len(goal) > 60:
        goal = goal[:60] + "..."

    evaluation = state.get("evaluation")
    if evaluation is not None:
        qualifier = evaluation.verdict.value
    else:
        agent_results = state.get("agent_results") or []
        confidence = _compute_mean_confidence(agent_results)
        qualifier = f"{confidence:.0%} confidence"

    return f"EDA Report: {goal} [{qualifier}]"


def _build_body(state: AgentState) -> str:
    """Build plain-text email body from state fields."""
    request = state["request"]
    goal = request.goal
    session_id = request.session_id
    timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    narrative: str = state.get("narrative") or ""
    key_insights: List[str] = state.get("key_insights") or []
    caveats: List[str] = state.get("caveats") or []
    agent_results: List[AgentResult] = state.get("agent_results") or []
    evaluation = state.get("evaluation")
    output_paths: dict = state.get("output_paths") or {}

    sep = "=" * 60

    # --- SUMMARY section (narrative truncated to 500 chars) ---
    if narrative and len(narrative) > 500:
        narrative_text = narrative[:500] + "..."
    else:
        narrative_text = narrative or "(No summary available.)"

    # --- KEY INSIGHTS section ---
    if key_insights:
        insights_text = "\n".join(
            f"{i + 1}. {insight}" for i, insight in enumerate(key_insights)
        )
    else:
        insights_text = "None identified."

    # --- QUALITY section ---
    if evaluation is not None:
        quality_text = (
            f"Verdict: {evaluation.verdict.value} | "
            f"Score: {evaluation.overall_score:.0%}"
        )
    else:
        confidence = _compute_mean_confidence(agent_results)
        quality_text = f"Confidence: {confidence:.0%}"

    # --- CAVEATS section ---
    if caveats:
        caveats_text = "\n".join(
            f"{i + 1}. {caveat}" for i, caveat in enumerate(caveats)
        )
    else:
        caveats_text = "None identified."

    report_path = output_paths.get("report", "not generated")

    body = (
        f"EDA Report — {goal}\n"
        f"Generated: {timestamp}\n"
        f"{sep}\n"
        f"\n"
        f"SUMMARY\n"
        f"{narrative_text}\n"
        f"\n"
        f"KEY INSIGHTS\n"
        f"{insights_text}\n"
        f"\n"
        f"{sep}\n"
        f"QUALITY\n"
        f"{quality_text}\n"
        f"\n"
        f"CAVEATS\n"
        f"{caveats_text}\n"
        f"\n"
        f"{sep}\n"
        f"Full report: {report_path}\n"
        f"Generated by EDA Agent | Session: {session_id}\n"
    )

    # Truncate to 2000 chars if needed
    if len(body) > 2000:
        body = body[:1997] + "..."

    return body


def draft_email(state: AgentState) -> str:
    """Generate a plain-text email draft from AgentState.

    Called by output_router_node when OutputType.EMAIL is requested.
    Writes to OUTPUT_DIR/<session_id>/email_<session_id>.txt.

    Returns the absolute path to the generated file.
    Raises RuntimeError on failure.
    """
    try:
        request = state["request"]
        session_id = request.session_id

        output_dir = Path(os.getenv("OUTPUT_DIR", "./output")) / session_id
        output_dir.mkdir(parents=True, exist_ok=True)

        subject = _build_subject(state)
        body = _build_body(state)

        output_path = output_dir / f"email_{session_id}.txt"
        content = f"Subject: {subject}\n\n{body}"
        output_path.write_text(content, encoding="utf-8")

        return str(output_path)

    except Exception as e:
        raise RuntimeError(f"draft_email failed: {e}") from e


def send_email(draft_path: str, to_address: str) -> bool:
    """Send the drafted email via SMTP.

    Returns True on success, False if SMTP is not configured or on any error.
    Never re-raises exceptions.
    """
    if not _smtp_configured():
        logger.warning("send_email: SMTP not configured — skipping send.")
        return False

    try:
        content = Path(draft_path).read_text(encoding="utf-8")
        lines = content.split("\n")

        # Parse subject from first line
        subject = ""
        if lines and lines[0].startswith("Subject: "):
            subject = lines[0][len("Subject: "):]

        # Body starts after first blank line
        body_start = 0
        for i, line in enumerate(lines):
            if line == "":
                body_start = i + 1
                break
        body = "\n".join(lines[body_start:])

        smtp_host = os.getenv("SMTP_HOST", "")
        smtp_port = int(os.getenv("SMTP_PORT", "587"))
        smtp_user = os.getenv("SMTP_USER", "")
        smtp_password = os.getenv("SMTP_PASSWORD", "")
        smtp_from = os.getenv("SMTP_FROM", "")

        msg = MIMEMultipart()
        msg["From"] = smtp_from
        msg["To"] = to_address
        msg["Subject"] = subject
        msg.attach(MIMEText(body, "plain"))

        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.starttls()
            server.login(smtp_user, smtp_password)
            server.sendmail(smtp_from, to_address, msg.as_string())

        return True

    except Exception as exc:
        logger.exception("send_email failed: %s", exc)
        return False
